server:
  port: 8888


spring:
  application:
    name: flower-freamwork
  boot:
    admin:
      client:
        url: http://localhost:8081
management:
  endpoints:
    web:
      exposure:
        include: "*"